version: '3.7'

services:
  instant_shit:
    image: pazka/instantshit
    ports:
      - 12121:80
    restart: unless-stopped
    volumes:
      - ./data:./data

  instant_shit_mom:
    image: pazka/instantshit
    ports:
      - 12122:80
    restart: unless-stopped
    volumes:
      - ./data:./data
